### PR TITLE
Bobs changes

### PR DESCRIPTION
**Pull request by rlwoodjr**
Please review changes

### CODE REVIEW

**Comment by benb1n** [comment]
This looks ok to me. Is it not showing what you'd expect it to show?

**Comment by rlwoodjr** [comment]
I actually posted it to openbuilds the first time. I deleted that one. too
much new stuff I need to learn.
Bob

**Comment by benb1n** [comment]
The typical process is the person you asked to review the PR will merge it using the "Merge pull request" button on this PR. Then it will be merged to the remote master (origin/master). To get these changes locally, you'll then need to switch your local branch to master and pull. Then you can create a new branch for the next thing you work on. I'll go ahead and merge this PR now...

**Comment by rlwoodjr** [comment]
Thanks!

**Pull request merged**
